### ISSUE TITLE
Using a query string to specify the site

### ISSUE THREAD

**Issue by chilloutalready** [rushpartners/fantasy-js-sdk#1]
I am not sure that this is the best idea. What if we have to host their subdomain? Additionally we may want to split up the hosting of sites and better to route with subdomains.

**Comment by davidianbonner** [comment]
This isn't used, we construct the the domain and I was tagging this to the end of the URL for no reason other than to do some testing.

They will pass in the subdomain in here instead of the URL: https://github.com/rushpartners/fantasy-js-sdk/blob/da4803d98dcca278350cb6f89e383cb6c6f70859/src/scratchpad/index.html#L10

So 

```javascript
    FantasySDK.init(token, 'redarmybet', {
        queryString: window.location.search,
    });
```

**Comment by chilloutalready** [comment]
👍
